### ISSUE TITLE
Questions about the returned p_aba and p_target

### ISSUE THREAD

**Issue by eriche2016** [kchen92/text2shape#1]
hi, Kevin , [line158](https://github.com/kchen92/text2shape/blob/6a8d6b3c395db71000ee7d0850f62d8e18ae9a75/lib/losses.py#L158) and [line174](https://github.com/kchen92/text2shape/blob/6a8d6b3c395db71000ee7d0850f62d8e18ae9a75/lib/losses.py#L174) in file ```losses.py```, and i noticted you have compute p_aba and p_target twice when LBA_model_type is 'MM', obviously they have different meanings, is it appropriate  to override the computed p_aba  and return the second p_aba when the lba model type is ```MM```

**Comment by kchen92** [comment]
Hi, thanks for your interest. I believe it does not matter, as long as the losses are being [set correctly](https://github.com/kchen92/text2shape/blob/6a8d6b3c395db71000ee7d0850f62d8e18ae9a75/lib/losses.py#L184).

The returned `p_aba` and `p_target` are only used to specify which tensors to print out during a `sess.run` call.
