### ISSUE TITLE
Question on validation techniques

### ISSUE THREAD

**Issue by eriche2016** [kchen92/text2shape#2]
Hi, chen, during validation, i found that you calculate the retrieval  metric based on a mixed score of  shape-to-shape, text-to-text, shape-to-text, etc, see [line](https://github.com/kchen92/text2shape/blob/6a8d6b3c395db71000ee7d0850f62d8e18ae9a75/lib/solver_encoder.py#L359), is that okay, or am i miss something?

**Comment by kchen92** [comment]
It is one way (among many) of evaluating the performance during training, so it should be OK.

**Comment by eriche2016** [comment]
Okay, got it. thanks for your quick reply.

**Comment by mingyangShang** [comment]
what do you mean "a mixed score of shape-shape, text-to-text, shape-to-text"? Given a text as query, the result can be Text or shape?

**Comment by kchen92** [comment]
He is referring to the validation part. Feel free to change the code as you like. When computing the final evaluation numbers, the text-text, shape-shape, and text-shape numbers are computed separately (and differently from in validation).
