### ISSUE TITLE
The performance of the code

### ISSUE THREAD

**Issue by eriche2016** [kchen92/text2shape#3]
Hi, Kelvin, I am running your code, but I got worse performances on primitive datasets than your paper reports. For example, for text to text retrieval, I noticed that you have reached 100 in terms of PR@1, However, I got only 70 (trained for 1000 epochs, on test set), can you give some tips on training the embeddings for the retrieval experiments?

**Comment by kchen92** [comment]
I just re-trained the model from this repo and it worked for me. I trained on the train set for 100k iterations. Note that the evaluation/validation that is performed during the train script is not entirely representative of the performance. To truly evaluate the model, you should generate the embeddings as indicated in the readme and then perform a separate evaluation on those generated embeddings.
