### ISSUE TITLE
How to split train/val/test dataset for primitives?

### ISSUE THREAD

**Issue by mingyangShang** [kchen92/text2shape#4]
I noticed that you are spliting train/val/test as 80%/10%/10% on primitives dataset, but i'm confused how you split it in detail? The primitives have 756 classes, 10 models for each class, and more than 200 captions for each class, because in primitive dataset, the captions are created for entire class, not for single model, so all models in a class share the captions. Am i right? If so, how do you split the primitives dataset? For example, if you choose model X for training, will you take all captions corrsponded to its class for training, or choose some parts of these captions also? I can't find the answer on the paper and code, so can you explain about this in detail? thanks very much!

**Comment by kchen92** [comment]
Yes, that is correct. I split the primitives dataset by the class. So, an orange torus with height 20 and radius 50 will only occur in one split (train or val or test), and it will not appear in any other splits. In other words, all captions and models corresponding to any particular class will only appear in one split.

**Comment by mingyangShang** [comment]
@kchen92 , Thanks for your reply, is that meaning none of test classes are seen when training? It's a little different from the common way in which we split some parts from all classes as training, and the others for testing, so that all classes will be considered in training phase.

**Comment by kchen92** [comment]
Thanks for the feedback. We split it this way to see if the model could generalize to unseen classes.

**Comment by mingyangShang** [comment]
ok, got it, thanks very much!
