### ISSUE TITLE
num_epochs argument on generate_text_embeddings.sh

### ISSUE THREAD

**Issue by ulucsahin** [kchen92/text2shape#6]
Hi,

I've been looking at the code and realized that "./tools/scripts/generate_text_embeddings.sh" is not using the "--num_epochs 10000" argument. It makes sense since the model is already trained in previous step and only being used for generating. Am I missing a point here by thinking that epochs are not used here? Or is it okay to omit "--num_epochs 10000" argument when executing "generate_text_embeddings.sh" ?  

Thank you very much.

**Comment by AmingWu** [comment]
@ulucsahin , could you share the test code? I run  ./tools/scripts/generate_text_embeddings.sh LAB1 outputs/shapenet/encoder_logdir/2020-05-04_23-39-54/model.ckpt-50 '--dataset shapenet --visit_weight 0.25 --lba_mode MM --num_epochs 10000 --lba_test_mode text --lba_unnormalize'. But it failed
